# Generated by Django 5.1.6 on 2025-04-05 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_title_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
